### ISSUE TITLE
Please update AFNetworking version in Podspec

### ISSUE THREAD

**Issue by donly** [arcam/CocoaUPnP#26]
Just update the `.podspec` file, change this line

> s.dependency 'AFNetworking', '~> 2.6'

to

> s.dependency 'AFNetworking' 

Many thanks!

**Comment by squarefrog** [comment]
Thanks - I will do in time, I haven't yet had time to read through and see if there are breaking changes in 3.0, so for now we'll stick to the last compatible version with 2.6.
