### ISSUE TITLE
How to create a normal UPnP server

### ISSUE THREAD

**Issue by mdfalcon104** [arcam/CocoaUPnP#27]
I am having in trouble with create a UPnP Server, but I don't know where to start. 

I see in the library there are classed: UPPEventServer.h,  UPPMediaServerDevice.h but I don't think they are correct class of UPnP instance. Can you hep me?

**Comment by squarefrog** [comment]
I think you misunderstand the purpose of this library. The library is intended to facilitate creation of a Control Point application.

If you want to create a server, I suggest reading through the UPnP documentation to see what would be involved.
