### ISSUE TITLE
MediaRendererDevice with empty services

### ISSUE THREAD

**Issue by LucasAdam** [arcam/CocoaUPnP#33]
Hi, 

I'm having trouble understanding how the parsing is working. When I try and detect my STB (or CPE or whatever the name is) here is what I receive : 
![capture d ecran 2016-09-29 a 15 10 42](https://cloud.githubusercontent.com/assets/9447241/18955295/1942201e-8657-11e6-9a23-2b9fbe6089cf.png)
As you can see, ControlService, ManagerService & avTransportService are all empty. Any idea why ?

**Comment by squarefrog** [comment]
Can you provide me with the units description XML? http://10.4.1.37:80/MediaRender/Info/description.xml

**Comment by squarefrog** [comment]
Those services are lazily loaded. When you go to use them they will populate. See [`UPPMediaRendererDevice.m`](https://github.com/arcam/CocoaUPnP/blob/0e8c413d2b1a69a72b4f0055ab9db95c95d8c677/CocoaUPnP/Models/UPPMediaRendererDevice.m#L28-L82)

**Comment by LucasAdam** [comment]
Alright I see it's working thanks. Quick question tho, would it work with AVTransport:2 ?

**Comment by squarefrog** [comment]
Good question! Of the top of my head I can't think what is different. The spec intends for services to be backwards compatible so for functions supported by AVTransport:1, you'll be just fine.
