### ISSUE TITLE
501 XML Error while setting AVTransportURI with parameters

### ISSUE THREAD

**Issue by LucasAdam** [arcam/CocoaUPnP#34]
Hi,

I'm facing an issue when setting AVTransportURI, the error I always get is a "501 - XML error".
When working with UPNP inspector (http://coherence.beebits.net/wiki/UPnP-Inspector) I don't have any problem.

Here is an exemple of URI I'm trying to set "vod://crid%3A%2F%2Fschange.com%2Fbetv.be%2FCTID000000141100/crid%3A%2F%2Fschange.com%2Fbetv.be%2FCTID000000141100%2Cimi%3A8a4e385d3f3d3ff02ac2d5fbcef5ffd9?trailer=no&position=1029890" 

I tried without the url parameters (trailer & position) and it's working fine. So clearly it's the problem here. Any idea how to fix this ?

**Comment by squarefrog** [comment]
Looks like you need to encode the `?` and `&` characters.

**Comment by LucasAdam** [comment]
The request works indeed if I encode the `?` and `&` however, it looks like the device doesn't give a damn about the parameters 😓.  Acts like I didn't give any. Any clues ?

**Comment by squarefrog** [comment]
That doesn't really surprise me. So the reason it needs encoding as they are special characters within XML, and they appear within XML tags.

**Comment by LucasAdam** [comment]
How comes it works without any issue with UPNP inspector that isn't even encoding `?`and `&`? What should I do for it to work with your amazing lib ? Thanks

**Comment by squarefrog** [comment]
Good question. Have you actually looked at the outgoing traffic from UPnP inspector? Chances are it is silently encoding the characters for you. 

That is probably something that should be handled by this library - I can't remember off the top of my head why we don't do that.

**Comment by LucasAdam** [comment]
Okay problem solved, was using `%26` when encoding `&`. Using `&amp;` works fine :) Thanks for helping me out mate 👍  !
