### ISSUE TITLE
Once a device is detected it's not detected again

### ISSUE THREAD

**Issue by LucasAdam** [arcam/CocoaUPnP#36]
Hey, I'm facing a small issue : when I start the discovery, and successfully find the device I want, if I then stop the discovery and start it again some times later (a matter of seconds/minutes), it won't find the device anymore. Is that normal ? 

Thanks :)

**Comment by squarefrog** [comment]
Yes - as `UPPDiscovery` already knows about the device. The only time it'll send out another notification is if the device sends a `BYEBYE` message then appears again.

You can fetch all the discovered devices with:

```
[[UPPDiscovery sharedInstance] availableDevices];
```

**Comment by LucasAdam** [comment]
Thank you for that clarification :)

**Comment by squarefrog** [comment]
No problem! 👍

**Comment by LucasAdam** [comment]
Is there a way to reset known devices myself ? Besides killing the app ?

**Comment by squarefrog** [comment]
Not currently, but it wouldn't be hard to add a `[discovery forgetAllDevices];` method. I'm curious though why you need it?

**Comment by LucasAdam** [comment]
Well I present to the user a list of detected devices he can choose as his default STB/CPE, however, 2 hours later if he's at his, let's say GF's house, I want him to only see devices availble there and not the ones he discovered earlier.

**Comment by squarefrog** [comment]
That makes sense. I've added a `[discover forgetAllKnownDevices];` method. I'll just wait for the travis result then push out a new release.

**Comment by LucasAdam** [comment]
Thanks a bunch. You rock man !

**Comment by squarefrog** [comment]
Just pushed `1.1.0` which has the method you need 🎉 🌮 

You may need to `$ pod repo update` to see it.
