### ISSUE TITLE
How to subscription event

### ISSUE THREAD

**Issue by duydatpham** [arcam/CocoaUPnP#41]
Hi friend,
pls help me, I dont know how to subscription event . if u can, pls show me a example 

Thanks

**Comment by debugholic** [comment]
That's easy.

Just add subscribeObserver to UPPEventSubscriptionManager as following.

`[[UPPEventSubscriptionManager sharedInstance] subscribeObserver:device toService:device.avTransportService completion:nil];`

You can received event through UPPEventSubscriptionDelegate protocol.

`- (void)eventReceived:(NSDictionary *)event`

I think maybe you want to subscribe 'LastChange' event and it is parsed UPPLastChangeParser.
What you have to do is getting keys and values from event dictionary.
If you want to subscribe other events, you should write those parsers. See OnoXML.

GOOD LUCK.

**Comment by duydatpham** [comment]
hi,
many thanks for replying me :)
But i check API, this function dont like you show me. (pls check image)
![screen shot 2017-03-14 at 09 53 39](https://cloud.githubusercontent.com/assets/5369097/23883931/6fafa17a-089c-11e7-9a58-0c9c53b22da4.png)

If i'm trying to call like you said, i see that 'GCDWebServer stopped' on the console (pls check image)
![screen shot 2017-03-14 at 09 58 32](https://cloud.githubusercontent.com/assets/5369097/23884050/fe342b28-089c-11e7-9c78-a248be95754a.png)
![screen shot 2017-03-14 at 09 58 53 copy](https://cloud.githubusercontent.com/assets/5369097/23884137/8dbda0a8-089d-11e7-8b7b-826e3cf427ff.png)

**Comment by squarefrog** [comment]
You must subscribe an object conforming to the `UPPEventSubscriptionDelegate`, to an existing service not a new one.
