### ISSUE TITLE
How to create and fetch the items in queue 

### ISSUE THREAD

**Issue by vishnunltr** [arcam/CocoaUPnP#43]
How to  add the  selected music items to queue and after adding the item in queue how to fetch the items in queue .Thanks

**Comment by squarefrog** [comment]
I'm not sure I understand your question. If you want to learn more about how to use UPnP, the [documentation](https://openconnectivity.org/developer/specifications/upnp-resources/upnp) is a good place to start.

How you create a queue is up to you. Typically you retain an array of `UPPMediaItem` objects.

**Comment by vishnunltr** [comment]
@squarefrog 
Thanks for reply. But i need to save the selected items in device like render device and fetch items from render device. If  i save selected items in array locally it shows selected items and selected item is playing correctly but  controls like next and previous commands not working.Plz check below code for next and previous commands .  I Do not want to save locally need to fetch from connected device .Is there any way to save and get the saved the items in render device.Help me!

for playing selected track:
[self.playbackManager playItem:item];

@next item:
 UPPAVTransportService *avTransport = [self.renderer avTransportService];
    [avTransport nextWithInstanceID:@"0" success:^(BOOL success, NSError *error) {
        if (!success) {
            NSLog(@"%s: Error sending next command: %@", __PRETTY_FUNCTION__, error);
        }
    }];
@previous item :
UPPAVTransportService *avTransport = [self.renderer avTransportService];
    [avTransport previousWithInstanceID:@"0" success:^(BOOL success, NSError *error) {
        if (!success) {
            NSLog(@"%s: Error sending previous command: %@", __PRETTY_FUNCTION__, error);
        }
    }];

**Comment by squarefrog** [comment]
It is up to you to handle next/previous logic. Very very few renderers support playlists. What I do is have an array of items, then when a user presses next, or previous, then handle that in the app by setting the new transport URI.
