### ISSUE TITLE
Media item title with or without extension

### ISSUE THREAD

**Issue by fabcan1** [arcam/CocoaUPnP#45]
Hi,
I don't know if it's an issue or not, but with some media server when I browse with ContentdirectorryService the itemtitle returned is with the extension (For example "matrix.avi") and with some other server is without (just "matrix").
For my app I need to have always the same result.
Dio you know what can I do?
Thank you.

**Comment by squarefrog** [comment]
Generally, this `itemTitle` is set by the media server itself. My guess here is that the file itself doesn’t have any metadata itself, so each media service reports the title slightly different. 

Unfortunately, there’s not an awful lot you can do about this as there are thousands of media servers, it would be impossible to test them all. You may have some luck doing a regex string replacement for the items title.

**Comment by fabcan1** [comment]
Thank you for this quick answer.
I will think for another way to manage that.
Thanks.
