### ISSUE TITLE
How to Broadcasting iPhone's media as the service side

### ISSUE THREAD

**Issue by ghost** [arcam/CocoaUPnP#55]
The current demo project works as a client side, it get media from other devices are broadcating. Now I want to setup a server side for broadcasting iphone's media, so other devices can connect and browsing this content.

**Comment by squarefrog** [comment]
That isn't currently supported. While not impossible it does pose several challenges:

1. You'd need to support at least the [ContentDirectory:1](http://upnp.org/specs/av/UPnP-av-ContentDirectory-v1-Service.pdf) service

2. You need to setup a web server to host responses and files

3. You don't have full access to the devices media from the `MediaPlayer` framework. This is the biggest issue for you. The only workaround is to stream the audio to a file on disk then use this with the web server

As a result, it is beyond the scope of this framework, I would recommend starting a seperate framework for this behaviour if you still want to go ahead.
