### ISSUE TITLE
LG Tvs : 714 - Illegal MIME-type

### ISSUE THREAD

**Issue by fabcan1** [arcam/CocoaUPnP#56]
Hello,

First thanks for this very usefull library.
Everything works fine for me except for LG tv when I try to read a video.

When I go on the TV and launch the file explorer I can read all of the movies shared by my media server. (Without my app)

But when from my app I try to read a movie I have always the same errors : _714 - Illegal MIME-type_ or sometimes _704 - Format not supported for playback_

This is only on this TV,
 I do the same thing on other TVs and that works great.

Maybe I do not write the correct code, for example I don't write the currentURIMetaData?

Thanks in advance for your help.

This is my code:

```
            TV.avTransportService()?.setAVTransportURI(url, currentURIMetaData: "", instanceID: "0", success: { (ok, err) in
                if let error = err {
                    print("Soucis de set URI",error)
                    completion(false)

                }else{
                    print("URI SET OK")
                    TV.avTransportService()?.play(withInstanceID: "0", success: { (success, error2) in
                        if let error2 = error2 {
                            print("Soucis de lecture",error2)
                            completion(false)
                           
                        }else{
                            print("lecture OK en cours")
                            if success == true{
                                completion(true)
                            }else{
                                completion(false)
                            }
                        }
                        
                        
                    })
                    
                }
            })
```

**Comment by squarefrog** [comment]
Hi there. `currentURIMetaData` is likely to be required by your TV. Try using `UPPMetadataHelper`:

```swift
guard let metaData = UPPMetadataForItem(yourItem) else { return }
```

**Comment by fabcan1** [comment]
Thank you sir!
That works great.
I didn't know UPPMetadataForItem.
