### ISSUE TITLE
Please add the supported UPnP version(s) to the docu (readme)

### ISSUE THREAD

**Issue by funnel20** [arcam/CocoaUPnP#58]
The UPnP forum has 3 versions of the Device Architecture. These are:
- 1.0, October 15, 2008, http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.0.pdf
- 1.0, October 15, 2008, http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.1.pdf
- 2.0, February 20, 2008, http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v2.0.pdf

Which one(s) is this library compatible with?

**Comment by squarefrog** [comment]
This uses v1.0, as is shown at the [top of the model headers](https://github.com/arcam/CocoaUPnP/blob/develop/CocoaUPnP/Models/UPPMediaRendererDevice.h#L10-L14).

All other versions are backwards compatible.
