### ISSUE TITLE
The bitrate of the song queried through CocoaUPnP is incorrect

### ISSUE THREAD

**Issue by lzwei123** [arcam/CocoaUPnP#66]
The BitRate in the song information obtained from Media Server is incorrect

**Comment by squarefrog** [comment]
Bitrate is sent by the media server, we display it as is. It should be expressed as bytes/second, as stated in the [Content Directory Service](http://upnp.org/specs/av/UPnP-av-ContentDirectory-v1-Service.pdf) specification. If this value is wrong you should inform the media server author.
